<?php

declare(strict_types=1);

namespace AppMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240530163257 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE answer (id SERIAL NOT NULL, contact_id INT NOT NULL, user_id INT NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DADD4A25E7A1254A ON answer (contact_id)');
        $this->addSql('CREATE INDEX IDX_DADD4A25A76ED395 ON answer (user_id)');
        $this->addSql('CREATE TABLE attach (id SERIAL NOT NULL, user_details_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, mime VARCHAR(255) NOT NULL, size INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DEC97C811C7DC1CE ON attach (user_details_id)');
        $this->addSql('CREATE TABLE category (id SERIAL NOT NULL, slug VARCHAR(255) DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(512) DEFAULT NULL, position SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE contact (id SERIAL NOT NULL, name VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, answers INT NOT NULL, phone VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, message TEXT NOT NULL, email VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE entry (id SERIAL NOT NULL, user_id INT DEFAULT NULL, slug VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, comments INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2B219D70989D9B62 ON entry (slug)');
        $this->addSql('CREATE INDEX IDX_2B219D70A76ED395 ON entry (user_id)');
        $this->addSql('CREATE INDEX idx ON entry (status, type)');
        $this->addSql('CREATE TABLE entry_attachment (id SERIAL NOT NULL, attach_id INT DEFAULT NULL, details_id INT DEFAULT NULL, in_use INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E1F59089E784F8B7 ON entry_attachment (attach_id)');
        $this->addSql('CREATE INDEX IDX_E1F59089BB1A0722 ON entry_attachment (details_id)');
        $this->addSql('CREATE TABLE entry_category (id SERIAL NOT NULL, entry_id INT DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_680BF989BA364942 ON entry_category (entry_id)');
        $this->addSql('CREATE INDEX IDX_680BF98912469DE2 ON entry_category (category_id)');
        $this->addSql('CREATE TABLE entry_details (id SERIAL NOT NULL, entry_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, content TEXT DEFAULT NULL, short_content TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5EC0A41DBA364942 ON entry_details (entry_id)');
        $this->addSql('CREATE TABLE faq (id SERIAL NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, visible INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE reset_password_request (id SERIAL NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('COMMENT ON COLUMN reset_password_request.requested_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN reset_password_request.expires_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store (id SERIAL NOT NULL, owner_id INT DEFAULT NULL, attach_id INT DEFAULT NULL, name VARCHAR(512) NOT NULL, address VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, slug VARCHAR(512) DEFAULT NULL, currency VARCHAR(5) DEFAULT NULL, website VARCHAR(1024) DEFAULT NULL, url VARCHAR(1024) DEFAULT NULL, description TEXT DEFAULT NULL, messages TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF575877989D9B62 ON store (slug)');
        $this->addSql('CREATE INDEX IDX_FF5758777E3C61F9 ON store (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FF575877E784F8B7 ON store (attach_id)');
        $this->addSql('COMMENT ON COLUMN store.messages IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE store_address (id SERIAL NOT NULL, customer_id INT DEFAULT NULL, line1 VARCHAR(255) NOT NULL, line2 VARCHAR(255) DEFAULT NULL, phone VARCHAR(50) DEFAULT NULL, country VARCHAR(5) NOT NULL, city VARCHAR(255) DEFAULT NULL, region VARCHAR(255) DEFAULT NULL, postal VARCHAR(50) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_14464E669395C3F3 ON store_address (customer_id)');
        $this->addSql('COMMENT ON COLUMN store_address.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_brand (id SERIAL NOT NULL, store_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(512) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_606CAF41B092A811 ON store_brand (store_id)');
        $this->addSql('CREATE TABLE store_category (id SERIAL NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(512) NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(512) DEFAULT NULL, level INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_383B663B989D9B62 ON store_category (slug)');
        $this->addSql('CREATE INDEX IDX_383B663B727ACA70 ON store_category (parent_id)');
        $this->addSql('COMMENT ON COLUMN store_category.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_category_product (id SERIAL NOT NULL, product_id INT DEFAULT NULL, category_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_682FD70D4584665A ON store_category_product (product_id)');
        $this->addSql('CREATE INDEX IDX_682FD70D12469DE2 ON store_category_product (category_id)');
        $this->addSql('CREATE TABLE store_coupon (id SERIAL NOT NULL, store_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, discount INT DEFAULT NULL, price NUMERIC(10, 2) DEFAULT NULL, event SMALLINT DEFAULT NULL, available INT NOT NULL, max_usage SMALLINT NOT NULL, type VARCHAR(50) NOT NULL, order_limit INT NOT NULL, promotion_text VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, expired_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A8A994B092A811 ON store_coupon (store_id)');
        $this->addSql('COMMENT ON COLUMN store_coupon.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN store_coupon.started_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN store_coupon.expired_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_coupon_store_product (store_coupon_id INT NOT NULL, store_product_id INT NOT NULL, PRIMARY KEY(store_coupon_id, store_product_id))');
        $this->addSql('CREATE INDEX IDX_73049F1D3B93F966 ON store_coupon_store_product (store_coupon_id)');
        $this->addSql('CREATE INDEX IDX_73049F1D6B6D3DB7 ON store_coupon_store_product (store_product_id)');
        $this->addSql('CREATE TABLE store_coupon_code (id SERIAL NOT NULL, coupon_id INT DEFAULT NULL, code VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E9BE9B0466C5951B ON store_coupon_code (coupon_id)');
        $this->addSql('CREATE TABLE store_coupon_usage (id SERIAL NOT NULL, coupon_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, coupon_code_id INT DEFAULT NULL, relation INT NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_29CC2AB466C5951B ON store_coupon_usage (coupon_id)');
        $this->addSql('CREATE INDEX IDX_29CC2AB49395C3F3 ON store_coupon_usage (customer_id)');
        $this->addSql('CREATE INDEX IDX_29CC2AB4C8B2BD81 ON store_coupon_usage (coupon_code_id)');
        $this->addSql('COMMENT ON COLUMN store_coupon_usage.used_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_customer (id SERIAL NOT NULL, member_id INT DEFAULT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, phone VARCHAR(100) NOT NULL, country VARCHAR(5) NOT NULL, email VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BF4EF1F37597D3FE ON store_customer (member_id)');
        $this->addSql('COMMENT ON COLUMN store_customer.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_customer_orders (id SERIAL NOT NULL, customer_id INT DEFAULT NULL, orders_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_359648719395C3F3 ON store_customer_orders (customer_id)');
        $this->addSql('CREATE INDEX IDX_35964871CFFE9AD6 ON store_customer_orders (orders_id)');
        $this->addSql('CREATE TABLE store_invoice (id SERIAL NOT NULL, orders_id INT DEFAULT NULL, payment_gateway_id INT DEFAULT NULL, number VARCHAR(50) NOT NULL, tax NUMERIC(10, 2) NOT NULL, amount NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_896D36A3CFFE9AD6 ON store_invoice (orders_id)');
        $this->addSql('CREATE INDEX IDX_896D36A362890FD5 ON store_invoice (payment_gateway_id)');
        $this->addSql('COMMENT ON COLUMN store_invoice.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_manufacturer (id SERIAL NOT NULL, store_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2A63CDE8B092A811 ON store_manufacturer (store_id)');
        $this->addSql('CREATE TABLE store_message (id SERIAL NOT NULL, parent_id INT DEFAULT NULL, store_id INT DEFAULT NULL, customer_id INT DEFAULT NULL, product_id INT DEFAULT NULL, orders_id INT DEFAULT NULL, priority VARCHAR(50) DEFAULT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AFB51198727ACA70 ON store_message (parent_id)');
        $this->addSql('CREATE INDEX IDX_AFB51198B092A811 ON store_message (store_id)');
        $this->addSql('CREATE INDEX IDX_AFB511989395C3F3 ON store_message (customer_id)');
        $this->addSql('CREATE INDEX IDX_AFB511984584665A ON store_message (product_id)');
        $this->addSql('CREATE INDEX IDX_AFB51198CFFE9AD6 ON store_message (orders_id)');
        $this->addSql('COMMENT ON COLUMN store_message.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN store_message.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_orders (id SERIAL NOT NULL, store_id INT DEFAULT NULL, number VARCHAR(50) NOT NULL, total NUMERIC(10, 2) DEFAULT NULL, session VARCHAR(255) DEFAULT NULL, status VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_81386B78B092A811 ON store_orders (store_id)');
        $this->addSql('COMMENT ON COLUMN store_orders.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_orders_product (id SERIAL NOT NULL, orders_id INT DEFAULT NULL, product_id INT DEFAULT NULL, size VARCHAR(100) DEFAULT NULL, color VARCHAR(100) DEFAULT NULL, quantity INT NOT NULL, discount INT DEFAULT NULL, cost NUMERIC(10, 2) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_35A96B08CFFE9AD6 ON store_orders_product (orders_id)');
        $this->addSql('CREATE INDEX IDX_35A96B084584665A ON store_orders_product (product_id)');
        $this->addSql('CREATE TABLE store_payment_gateway (id SERIAL NOT NULL, name VARCHAR(100) NOT NULL, summary TEXT NOT NULL, active BOOLEAN NOT NULL, icon VARCHAR(50) NOT NULL, slug VARCHAR(255) NOT NULL, handler_text VARCHAR(100) NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE store_payment_gateway_store (id SERIAL NOT NULL, gateway_id INT DEFAULT NULL, store_id INT DEFAULT NULL, active BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A9D00729577F8E00 ON store_payment_gateway_store (gateway_id)');
        $this->addSql('CREATE INDEX IDX_A9D00729B092A811 ON store_payment_gateway_store (store_id)');
        $this->addSql('CREATE TABLE store_product (id SERIAL NOT NULL, store_id INT DEFAULT NULL, name VARCHAR(512) NOT NULL, description TEXT NOT NULL, slug VARCHAR(512) DEFAULT NULL, quantity INT NOT NULL, cost NUMERIC(10, 2) NOT NULL, short_name VARCHAR(80) NOT NULL, discount NUMERIC(10, 2) DEFAULT NULL, sku VARCHAR(255) DEFAULT NULL, pckg_quantity INT DEFAULT NULL, fee NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CA42254A989D9B62 ON store_product (slug)');
        $this->addSql('CREATE INDEX IDX_CA42254AB092A811 ON store_product (store_id)');
        $this->addSql('CREATE TABLE store_product_attach (id SERIAL NOT NULL, product_id INT DEFAULT NULL, attach_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AB2320FB4584665A ON store_product_attach (product_id)');
        $this->addSql('CREATE INDEX IDX_AB2320FBE784F8B7 ON store_product_attach (attach_id)');
        $this->addSql('CREATE TABLE store_product_attribute (id SERIAL NOT NULL, product_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, in_front INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F5CD1B364584665A ON store_product_attribute (product_id)');
        $this->addSql('COMMENT ON COLUMN store_product_attribute.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE store_product_attribute_value (id SERIAL NOT NULL, attribute_id INT DEFAULT NULL, value VARCHAR(255) NOT NULL, extra JSON NOT NULL, in_use INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6574716BB6E62EFA ON store_product_attribute_value (attribute_id)');
        $this->addSql('CREATE TABLE store_product_brand (id SERIAL NOT NULL, product_id INT DEFAULT NULL, brand_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CAD1F9A4584665A ON store_product_brand (product_id)');
        $this->addSql('CREATE INDEX IDX_9CAD1F9A44F5D008 ON store_product_brand (brand_id)');
        $this->addSql('CREATE TABLE store_product_manufacturer (id SERIAL NOT NULL, product_id INT DEFAULT NULL, manufacturer_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81A8E1564584665A ON store_product_manufacturer (product_id)');
        $this->addSql('CREATE INDEX IDX_81A8E156A23B42D ON store_product_manufacturer (manufacturer_id)');
        $this->addSql('CREATE TABLE store_product_supplier (id SERIAL NOT NULL, product_id INT DEFAULT NULL, supplier_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2C2795374584665A ON store_product_supplier (product_id)');
        $this->addSql('CREATE INDEX IDX_2C2795372ADD6D8C ON store_product_supplier (supplier_id)');
        $this->addSql('CREATE TABLE store_social (id SERIAL NOT NULL, store_id INT DEFAULT NULL, source VARCHAR(4096) NOT NULL, source_name VARCHAR(255) NOT NULL, is_active BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_15767711B092A811 ON store_social (store_id)');
        $this->addSql('CREATE TABLE store_supplier (id SERIAL NOT NULL, store_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, country VARCHAR(3) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A55D1384B092A811 ON store_supplier (store_id)');
        $this->addSql('CREATE TABLE store_wishlist (id SERIAL NOT NULL, customer_id INT DEFAULT NULL, product_id INT DEFAULT NULL, store_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A29655CB9395C3F3 ON store_wishlist (customer_id)');
        $this->addSql('CREATE INDEX IDX_A29655CB4584665A ON store_wishlist (product_id)');
        $this->addSql('CREATE INDEX IDX_A29655CBB092A811 ON store_wishlist (store_id)');
        $this->addSql('COMMENT ON COLUMN store_wishlist.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "user" (id SERIAL NOT NULL, attach_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, ip VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E784F8B7 ON "user" (attach_id)');
        $this->addSql('CREATE TABLE user_details (id SERIAL NOT NULL, user_id INT DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, about TEXT DEFAULT NULL, date_birth TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2A2B1580A76ED395 ON user_details (user_id)');
        $this->addSql('CREATE TABLE user_social (id SERIAL NOT NULL, details_id INT DEFAULT NULL, facebook_profile VARCHAR(512) DEFAULT NULL, twitter_profile VARCHAR(512) DEFAULT NULL, instagram_profile VARCHAR(512) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1433FABABB1A0722 ON user_social (details_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE OR REPLACE FUNCTION notify_messenger_messages() RETURNS TRIGGER AS $$
            BEGIN
                PERFORM pg_notify(\'messenger_messages\', NEW.queue_name::text);
                RETURN NEW;
            END;
        $$ LANGUAGE plpgsql;');
        $this->addSql('DROP TRIGGER IF EXISTS notify_trigger ON messenger_messages;');
        $this->addSql('CREATE TRIGGER notify_trigger AFTER INSERT OR UPDATE ON messenger_messages FOR EACH ROW EXECUTE PROCEDURE notify_messenger_messages();');
        $this->addSql('CREATE TABLE rememberme_token (series VARCHAR(88) NOT NULL, value VARCHAR(88) NOT NULL, lastUsed TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, class VARCHAR(100) NOT NULL, username VARCHAR(200) NOT NULL, PRIMARY KEY(series))');
        $this->addSql('COMMENT ON COLUMN rememberme_token.lastUsed IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25E7A1254A FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE answer ADD CONSTRAINT FK_DADD4A25A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE attach ADD CONSTRAINT FK_DEC97C811C7DC1CE FOREIGN KEY (user_details_id) REFERENCES user_details (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entry ADD CONSTRAINT FK_2B219D70A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entry_attachment ADD CONSTRAINT FK_E1F59089E784F8B7 FOREIGN KEY (attach_id) REFERENCES attach (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entry_attachment ADD CONSTRAINT FK_E1F59089BB1A0722 FOREIGN KEY (details_id) REFERENCES entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entry_category ADD CONSTRAINT FK_680BF989BA364942 FOREIGN KEY (entry_id) REFERENCES entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entry_category ADD CONSTRAINT FK_680BF98912469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE entry_details ADD CONSTRAINT FK_5EC0A41DBA364942 FOREIGN KEY (entry_id) REFERENCES entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store ADD CONSTRAINT FK_FF5758777E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store ADD CONSTRAINT FK_FF575877E784F8B7 FOREIGN KEY (attach_id) REFERENCES attach (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_address ADD CONSTRAINT FK_14464E669395C3F3 FOREIGN KEY (customer_id) REFERENCES store_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_brand ADD CONSTRAINT FK_606CAF41B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_category ADD CONSTRAINT FK_383B663B727ACA70 FOREIGN KEY (parent_id) REFERENCES store_category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_category_product ADD CONSTRAINT FK_682FD70D4584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_category_product ADD CONSTRAINT FK_682FD70D12469DE2 FOREIGN KEY (category_id) REFERENCES store_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_coupon ADD CONSTRAINT FK_A8A994B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_coupon_store_product ADD CONSTRAINT FK_73049F1D3B93F966 FOREIGN KEY (store_coupon_id) REFERENCES store_coupon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_coupon_store_product ADD CONSTRAINT FK_73049F1D6B6D3DB7 FOREIGN KEY (store_product_id) REFERENCES store_product (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_coupon_code ADD CONSTRAINT FK_E9BE9B0466C5951B FOREIGN KEY (coupon_id) REFERENCES store_coupon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_coupon_usage ADD CONSTRAINT FK_29CC2AB466C5951B FOREIGN KEY (coupon_id) REFERENCES store_coupon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_coupon_usage ADD CONSTRAINT FK_29CC2AB49395C3F3 FOREIGN KEY (customer_id) REFERENCES store_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_coupon_usage ADD CONSTRAINT FK_29CC2AB4C8B2BD81 FOREIGN KEY (coupon_code_id) REFERENCES store_coupon_code (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_customer ADD CONSTRAINT FK_BF4EF1F37597D3FE FOREIGN KEY (member_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_customer_orders ADD CONSTRAINT FK_359648719395C3F3 FOREIGN KEY (customer_id) REFERENCES store_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_customer_orders ADD CONSTRAINT FK_35964871CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES store_orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_invoice ADD CONSTRAINT FK_896D36A3CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES store_orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_invoice ADD CONSTRAINT FK_896D36A362890FD5 FOREIGN KEY (payment_gateway_id) REFERENCES store_payment_gateway (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_manufacturer ADD CONSTRAINT FK_2A63CDE8B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_message ADD CONSTRAINT FK_AFB51198727ACA70 FOREIGN KEY (parent_id) REFERENCES store_message (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_message ADD CONSTRAINT FK_AFB51198B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_message ADD CONSTRAINT FK_AFB511989395C3F3 FOREIGN KEY (customer_id) REFERENCES store_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_message ADD CONSTRAINT FK_AFB511984584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_message ADD CONSTRAINT FK_AFB51198CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES store_orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_orders ADD CONSTRAINT FK_81386B78B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_orders_product ADD CONSTRAINT FK_35A96B08CFFE9AD6 FOREIGN KEY (orders_id) REFERENCES store_orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_orders_product ADD CONSTRAINT FK_35A96B084584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_payment_gateway_store ADD CONSTRAINT FK_A9D00729577F8E00 FOREIGN KEY (gateway_id) REFERENCES store_payment_gateway (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_payment_gateway_store ADD CONSTRAINT FK_A9D00729B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product ADD CONSTRAINT FK_CA42254AB092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_attach ADD CONSTRAINT FK_AB2320FB4584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_attach ADD CONSTRAINT FK_AB2320FBE784F8B7 FOREIGN KEY (attach_id) REFERENCES attach (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_attribute ADD CONSTRAINT FK_F5CD1B364584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_attribute_value ADD CONSTRAINT FK_6574716BB6E62EFA FOREIGN KEY (attribute_id) REFERENCES store_product_attribute (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_brand ADD CONSTRAINT FK_9CAD1F9A4584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_brand ADD CONSTRAINT FK_9CAD1F9A44F5D008 FOREIGN KEY (brand_id) REFERENCES store_brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_manufacturer ADD CONSTRAINT FK_81A8E1564584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_manufacturer ADD CONSTRAINT FK_81A8E156A23B42D FOREIGN KEY (manufacturer_id) REFERENCES store_manufacturer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_supplier ADD CONSTRAINT FK_2C2795374584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_product_supplier ADD CONSTRAINT FK_2C2795372ADD6D8C FOREIGN KEY (supplier_id) REFERENCES store_supplier (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_social ADD CONSTRAINT FK_15767711B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_supplier ADD CONSTRAINT FK_A55D1384B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_wishlist ADD CONSTRAINT FK_A29655CB9395C3F3 FOREIGN KEY (customer_id) REFERENCES store_customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_wishlist ADD CONSTRAINT FK_A29655CB4584665A FOREIGN KEY (product_id) REFERENCES store_product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE store_wishlist ADD CONSTRAINT FK_A29655CBB092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649E784F8B7 FOREIGN KEY (attach_id) REFERENCES attach (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_details ADD CONSTRAINT FK_2A2B1580A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_social ADD CONSTRAINT FK_1433FABABB1A0722 FOREIGN KEY (details_id) REFERENCES user_details (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A25E7A1254A');
        $this->addSql('ALTER TABLE answer DROP CONSTRAINT FK_DADD4A25A76ED395');
        $this->addSql('ALTER TABLE attach DROP CONSTRAINT FK_DEC97C811C7DC1CE');
        $this->addSql('ALTER TABLE entry DROP CONSTRAINT FK_2B219D70A76ED395');
        $this->addSql('ALTER TABLE entry_attachment DROP CONSTRAINT FK_E1F59089E784F8B7');
        $this->addSql('ALTER TABLE entry_attachment DROP CONSTRAINT FK_E1F59089BB1A0722');
        $this->addSql('ALTER TABLE entry_category DROP CONSTRAINT FK_680BF989BA364942');
        $this->addSql('ALTER TABLE entry_category DROP CONSTRAINT FK_680BF98912469DE2');
        $this->addSql('ALTER TABLE entry_details DROP CONSTRAINT FK_5EC0A41DBA364942');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE store DROP CONSTRAINT FK_FF5758777E3C61F9');
        $this->addSql('ALTER TABLE store DROP CONSTRAINT FK_FF575877E784F8B7');
        $this->addSql('ALTER TABLE store_address DROP CONSTRAINT FK_14464E669395C3F3');
        $this->addSql('ALTER TABLE store_brand DROP CONSTRAINT FK_606CAF41B092A811');
        $this->addSql('ALTER TABLE store_category DROP CONSTRAINT FK_383B663B727ACA70');
        $this->addSql('ALTER TABLE store_category_product DROP CONSTRAINT FK_682FD70D4584665A');
        $this->addSql('ALTER TABLE store_category_product DROP CONSTRAINT FK_682FD70D12469DE2');
        $this->addSql('ALTER TABLE store_coupon DROP CONSTRAINT FK_A8A994B092A811');
        $this->addSql('ALTER TABLE store_coupon_store_product DROP CONSTRAINT FK_73049F1D3B93F966');
        $this->addSql('ALTER TABLE store_coupon_store_product DROP CONSTRAINT FK_73049F1D6B6D3DB7');
        $this->addSql('ALTER TABLE store_coupon_code DROP CONSTRAINT FK_E9BE9B0466C5951B');
        $this->addSql('ALTER TABLE store_coupon_usage DROP CONSTRAINT FK_29CC2AB466C5951B');
        $this->addSql('ALTER TABLE store_coupon_usage DROP CONSTRAINT FK_29CC2AB49395C3F3');
        $this->addSql('ALTER TABLE store_coupon_usage DROP CONSTRAINT FK_29CC2AB4C8B2BD81');
        $this->addSql('ALTER TABLE store_customer DROP CONSTRAINT FK_BF4EF1F37597D3FE');
        $this->addSql('ALTER TABLE store_customer_orders DROP CONSTRAINT FK_359648719395C3F3');
        $this->addSql('ALTER TABLE store_customer_orders DROP CONSTRAINT FK_35964871CFFE9AD6');
        $this->addSql('ALTER TABLE store_invoice DROP CONSTRAINT FK_896D36A3CFFE9AD6');
        $this->addSql('ALTER TABLE store_invoice DROP CONSTRAINT FK_896D36A362890FD5');
        $this->addSql('ALTER TABLE store_manufacturer DROP CONSTRAINT FK_2A63CDE8B092A811');
        $this->addSql('ALTER TABLE store_message DROP CONSTRAINT FK_AFB51198727ACA70');
        $this->addSql('ALTER TABLE store_message DROP CONSTRAINT FK_AFB51198B092A811');
        $this->addSql('ALTER TABLE store_message DROP CONSTRAINT FK_AFB511989395C3F3');
        $this->addSql('ALTER TABLE store_message DROP CONSTRAINT FK_AFB511984584665A');
        $this->addSql('ALTER TABLE store_message DROP CONSTRAINT FK_AFB51198CFFE9AD6');
        $this->addSql('ALTER TABLE store_orders DROP CONSTRAINT FK_81386B78B092A811');
        $this->addSql('ALTER TABLE store_orders_product DROP CONSTRAINT FK_35A96B08CFFE9AD6');
        $this->addSql('ALTER TABLE store_orders_product DROP CONSTRAINT FK_35A96B084584665A');
        $this->addSql('ALTER TABLE store_payment_gateway_store DROP CONSTRAINT FK_A9D00729577F8E00');
        $this->addSql('ALTER TABLE store_payment_gateway_store DROP CONSTRAINT FK_A9D00729B092A811');
        $this->addSql('ALTER TABLE store_product DROP CONSTRAINT FK_CA42254AB092A811');
        $this->addSql('ALTER TABLE store_product_attach DROP CONSTRAINT FK_AB2320FB4584665A');
        $this->addSql('ALTER TABLE store_product_attach DROP CONSTRAINT FK_AB2320FBE784F8B7');
        $this->addSql('ALTER TABLE store_product_attribute DROP CONSTRAINT FK_F5CD1B364584665A');
        $this->addSql('ALTER TABLE store_product_attribute_value DROP CONSTRAINT FK_6574716BB6E62EFA');
        $this->addSql('ALTER TABLE store_product_brand DROP CONSTRAINT FK_9CAD1F9A4584665A');
        $this->addSql('ALTER TABLE store_product_brand DROP CONSTRAINT FK_9CAD1F9A44F5D008');
        $this->addSql('ALTER TABLE store_product_manufacturer DROP CONSTRAINT FK_81A8E1564584665A');
        $this->addSql('ALTER TABLE store_product_manufacturer DROP CONSTRAINT FK_81A8E156A23B42D');
        $this->addSql('ALTER TABLE store_product_supplier DROP CONSTRAINT FK_2C2795374584665A');
        $this->addSql('ALTER TABLE store_product_supplier DROP CONSTRAINT FK_2C2795372ADD6D8C');
        $this->addSql('ALTER TABLE store_social DROP CONSTRAINT FK_15767711B092A811');
        $this->addSql('ALTER TABLE store_supplier DROP CONSTRAINT FK_A55D1384B092A811');
        $this->addSql('ALTER TABLE store_wishlist DROP CONSTRAINT FK_A29655CB9395C3F3');
        $this->addSql('ALTER TABLE store_wishlist DROP CONSTRAINT FK_A29655CB4584665A');
        $this->addSql('ALTER TABLE store_wishlist DROP CONSTRAINT FK_A29655CBB092A811');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649E784F8B7');
        $this->addSql('ALTER TABLE user_details DROP CONSTRAINT FK_2A2B1580A76ED395');
        $this->addSql('ALTER TABLE user_social DROP CONSTRAINT FK_1433FABABB1A0722');
        $this->addSql('DROP TABLE answer');
        $this->addSql('DROP TABLE attach');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE entry');
        $this->addSql('DROP TABLE entry_attachment');
        $this->addSql('DROP TABLE entry_category');
        $this->addSql('DROP TABLE entry_details');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE store');
        $this->addSql('DROP TABLE store_address');
        $this->addSql('DROP TABLE store_brand');
        $this->addSql('DROP TABLE store_category');
        $this->addSql('DROP TABLE store_category_product');
        $this->addSql('DROP TABLE store_coupon');
        $this->addSql('DROP TABLE store_coupon_store_product');
        $this->addSql('DROP TABLE store_coupon_code');
        $this->addSql('DROP TABLE store_coupon_usage');
        $this->addSql('DROP TABLE store_customer');
        $this->addSql('DROP TABLE store_customer_orders');
        $this->addSql('DROP TABLE store_invoice');
        $this->addSql('DROP TABLE store_manufacturer');
        $this->addSql('DROP TABLE store_message');
        $this->addSql('DROP TABLE store_orders');
        $this->addSql('DROP TABLE store_orders_product');
        $this->addSql('DROP TABLE store_payment_gateway');
        $this->addSql('DROP TABLE store_payment_gateway_store');
        $this->addSql('DROP TABLE store_product');
        $this->addSql('DROP TABLE store_product_attach');
        $this->addSql('DROP TABLE store_product_attribute');
        $this->addSql('DROP TABLE store_product_attribute_value');
        $this->addSql('DROP TABLE store_product_brand');
        $this->addSql('DROP TABLE store_product_manufacturer');
        $this->addSql('DROP TABLE store_product_supplier');
        $this->addSql('DROP TABLE store_social');
        $this->addSql('DROP TABLE store_supplier');
        $this->addSql('DROP TABLE store_wishlist');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_details');
        $this->addSql('DROP TABLE user_social');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('DROP TABLE rememberme_token');
    }
}
